### ISSUE TITLE
Code Block CSS issue.

### ISSUE THREAD

**Issue by milkshakeuk** [aurelia/site-generator#12]
Code Blocks now hide content:
Browsers Tested:
Chrome Version 69.0.3497.100 (Official Build) (64-bit)
Microsoft Edge 42.17134.1.0

![image](https://user-images.githubusercontent.com/1087376/48944990-b5a0b400-ef20-11e8-8666-5d253866e359.png)

its the introduction of [this line](https://github.com/aurelia/site-generator/commit/9bebf967634cda5c2625c693f3b2e257b0fe3c68#diff-bc98f8895cc08b754a7f4491525b216cR376) that caused it.

![image](https://user-images.githubusercontent.com/1087376/48945077-f00a5100-ef20-11e8-892f-bed98174d3fd.png)

**Comment by EisenbergEffect** [comment]
I can't reproduce this on Chrome, FF, Safari, or Brave and I don't have Edge available to me at the moment. Can you try clear cache/hard refresh to make sure this is actually an issue?

**Comment by milkshakeuk** [comment]
@EisenbergEffect interestingly enough I have checked again, in chrome and edge and its working fine, perhaps it was cached after all strange that it was identical in both Edge and Chrome!

...Actually now that I think back I guess its possible its related to the way windows 10 handles switching resolutions since my laptop screen is 4k (scaled to 200%) but at the time I was using the dock with 2 1080p screens (scaled at 100%) attached and that's when I saw the issue.

😣
