### ISSUE TITLE
Point from HTTP-Client docs to DI

### ISSUE THREAD

**Issue by Ryuno-Ki** [aurelia/site-generator#30]
Hey there!

I'm currently porting a small demo over to Aurelia from Angular 9 and love it so far!
I'm not sure, whether this repo is still used for updating the website, but …

**What is the motivation / use case for changing the behavior?**
In [HTTP Services](https://github.com/aurelia/site-generator/blob/147972ad43789b03d5d389862df61472676ddd71/lib/app/docs/plugins/http-services/index.html) you are currently describing, how to build AJAX requests.

You also recommend (typo in the docs!) to:

> Instead, we reccommend that you create one or more service classes that encapsulate all HTTP access behind a friendly, application-specific API.

I'd suggest to place a link there to [Dependency Injection](https://aurelia.io/docs/fundamentals/dependency-injection), because that would describe *how* the service class would be written.

I discovered the page via a DDG-Search finally.

Thanks for making Aurelia :-)
The project evolved way better (watching your progress since the Skeleton times ;-) )

**Comment by EisenbergEffect** [comment]
@Ryuno-Ki We've moved the actual documentation content. It now resides in a `documentation` repo: https://github.com/aurelia/documentation

Here's the link to the http article: https://github.com/aurelia/documentation/blob/master/current/en-us/7.%20plugins/1.%20http-services.md

We've love for you to make a contribution there based on your feedback 😄

**Comment by Ryuno-Ki** [comment]
Hey @EisenbergEffect,

ah, there it is! May I suggest to update this repo's README then to point to the new destination?
Going to reopen this issue there (won't get a PR in today, I'm afraid).

**Comment by EisenbergEffect** [comment]
Pushed an update to the repo. Thanks!
